-- Schema of the embedding tables (pgvector). The embedding dumps (dump_embeddings_*.sql.gz) are data-only:
-- restore_production_data.sh applies this file first. Regenerated by export_production_data.sh.
CREATE EXTENSION IF NOT EXISTS vector;
--
-- PostgreSQL database dump
--


-- Dumped from database version 16.10 (Debian 16.10-1.pgdg12+1)
-- Dumped by pg_dump version 16.10 (Debian 16.10-1.pgdg12+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: product_embeddings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.product_embeddings (
    id uuid NOT NULL,
    product_id uuid NOT NULL,
    image_path character varying(500) NOT NULL,
    sample_type character varying(20) NOT NULL,
    embedding public.vector(384) NOT NULL,
    embedding_model character varying(200) NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ck_product_embeddings_sample_type CHECK (((sample_type)::text = ANY ((ARRAY['catalog'::character varying, 'augmented'::character varying, 'real'::character varying, 'customer'::character varying])::text[])))
);


--
-- Name: product_embeddings_v2; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.product_embeddings_v2 (
    id uuid NOT NULL,
    product_id uuid NOT NULL,
    image_path character varying(500) NOT NULL,
    sample_type character varying(20) NOT NULL,
    embedding public.vector(384) NOT NULL,
    embedding_model character varying(200) NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT product_embeddings_v2_sample_type_check CHECK (((sample_type)::text = ANY ((ARRAY['catalog'::character varying, 'augmented'::character varying, 'real'::character varying, 'customer'::character varying])::text[])))
);


--
-- Name: product_embeddings_v3; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.product_embeddings_v3 (
    id uuid NOT NULL,
    product_id uuid NOT NULL,
    image_path character varying(500) NOT NULL,
    sample_type character varying(20) NOT NULL,
    aug_name character varying(50) DEFAULT 'catalog'::character varying NOT NULL,
    aug_seed integer DEFAULT 0 NOT NULL,
    embedding public.vector(768) NOT NULL,
    embedding_model character varying(200) NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT product_embeddings_v3_sample_type_check CHECK (((sample_type)::text = ANY ((ARRAY['catalog'::character varying, 'augmented'::character varying, 'real'::character varying, 'customer'::character varying])::text[])))
);


--
-- Name: product_embeddings_v4; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.product_embeddings_v4 (
    id uuid NOT NULL,
    product_id uuid NOT NULL,
    image_path character varying(500) NOT NULL,
    sample_type character varying(20) NOT NULL,
    aug_name character varying(50) DEFAULT 'catalog'::character varying NOT NULL,
    aug_seed integer DEFAULT 0 NOT NULL,
    embedding public.vector(768) NOT NULL,
    embedding_model character varying(200) NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT product_embeddings_v4_sample_type_check CHECK (((sample_type)::text = ANY ((ARRAY['catalog'::character varying, 'augmented'::character varying, 'real'::character varying, 'customer'::character varying])::text[])))
);


--
-- Name: product_embeddings pk_product_embeddings; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_embeddings
    ADD CONSTRAINT pk_product_embeddings PRIMARY KEY (id);


--
-- Name: product_embeddings_v2 product_embeddings_v2_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_embeddings_v2
    ADD CONSTRAINT product_embeddings_v2_pkey PRIMARY KEY (id);


--
-- Name: product_embeddings_v3 product_embeddings_v3_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_embeddings_v3
    ADD CONSTRAINT product_embeddings_v3_pkey PRIMARY KEY (id);


--
-- Name: product_embeddings_v4 product_embeddings_v4_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_embeddings_v4
    ADD CONSTRAINT product_embeddings_v4_pkey PRIMARY KEY (id);


--
-- Name: ix_product_embeddings_product_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_product_embeddings_product_id ON public.product_embeddings USING btree (product_id);


--
-- Name: ix_product_embeddings_sample_type; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_product_embeddings_sample_type ON public.product_embeddings USING btree (sample_type);


--
-- Name: ix_product_embeddings_v2_product_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_product_embeddings_v2_product_id ON public.product_embeddings_v2 USING btree (product_id);


--
-- Name: ix_product_embeddings_v2_sample_type; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_product_embeddings_v2_sample_type ON public.product_embeddings_v2 USING btree (sample_type);


--
-- Name: ix_product_embeddings_v3_product_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_product_embeddings_v3_product_id ON public.product_embeddings_v3 USING btree (product_id);


--
-- Name: ix_product_embeddings_v3_sample_type; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_product_embeddings_v3_sample_type ON public.product_embeddings_v3 USING btree (sample_type);


--
-- Name: ix_product_embeddings_v4_product_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_product_embeddings_v4_product_id ON public.product_embeddings_v4 USING btree (product_id);


--
-- Name: ix_product_embeddings_v4_sample_type; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_product_embeddings_v4_sample_type ON public.product_embeddings_v4 USING btree (sample_type);


--
-- Name: product_embeddings fk_product_embeddings_product_id_products; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_embeddings
    ADD CONSTRAINT fk_product_embeddings_product_id_products FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE CASCADE;


--
-- Name: product_embeddings_v2 product_embeddings_v2_product_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_embeddings_v2
    ADD CONSTRAINT product_embeddings_v2_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE CASCADE;


--
-- Name: product_embeddings_v3 product_embeddings_v3_product_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_embeddings_v3
    ADD CONSTRAINT product_embeddings_v3_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE CASCADE;


--
-- Name: product_embeddings_v4 product_embeddings_v4_product_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_embeddings_v4
    ADD CONSTRAINT product_embeddings_v4_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--


